import React, { useMemo, useRef, useState, useEffect } from 'react';

interface CommandDashboardBackgroundProps {
    detachmentId?: string | null;
}

export const CommandDashboardBackground: React.FC<CommandDashboardBackgroundProps> = ({ detachmentId }) => {
    const interceptSets = {
        galley: [
            "[COMM] GALLEY-NET :: HEY, WHO WAS SUPPOSED TO CLEAN THE KITCHEN AREA? IT SMELLS LIKE DECAYING RAT IN HERE. IF I HAVE TO SCRUB SOY-PASTE OFF THE BULKHEADS ONE MORE TIME, SOMEONE IS GETTING JETTISONED.",
            "[COMM] GALLEY-NET :: WHOEVER IS STEALING THE REAL SUGAR FROM THE OFFICER'S MESS: WE HAVE CAMERAS. JUST BECAUSE WE'RE IN THE PERIPHERY DOESN'T MEAN WE'RE SAVAGES.",
            "[SIGNAL] MESS-HALL :: VENDING MACHINE 4 IS OUT OF QUIAFF-COLA. AGAIN. I'M NOT DRINKING THE RECYCLED WATER WITHOUT FLAVORING.",
            "[DATA] SUPPLY-LOG :: MOISTURE RECLAIMERS ARE AT 40%. SOMEONE TELL THE MECHWARRIORS THE SALAD BAR IS CLOSED UNTIL WE REACH THE JUMP POINT.",
            "[COMM] GALLEY-NET :: IF THE CHEF PUTS ONE MORE 'RECONSTITUTED PROTEIN BLOCK' ON MY PLATE, I AM GOING TO START EATING THE SHIP'S VENTILATION FILTERS.",
            "[ANNOUNCE] MESS-HALL :: UNIT CARD TOURNAMENT STARTS FRIDAY. PRIZE IS A DOUBLE RATION OF ACTUAL COFFEE AND A WEEK OF NO KITCHEN DUTY.",
            "[SIGNAL] MESS-HALL :: DOES ANYONE KNOW WHY THE SYNTHETIC MEAT DISPENSER IS MAKING THAT WET THUDDING SOUND? IT'S STARTING TO SMELL LIKE BURNT RUBBER.",
            "[COMM] GALLEY-NET :: STOP LEAVING YOUR UNWASHED MUGS ON THE COUNTER. THIS IS A MESS HALL, NOT A LANDFILL.",
            "[DATA] SUPPLY-LOG :: ALERT: RECYCLED WATER TASTES METALLIC TODAY. CHECK THE ION FILTERS IN SECTOR 4 IMMEDIATATEY.",
            "[COMM] GALLEY-NET :: TO THE PERSON WHO LEFT THE HALF-EATEN NUTRI-SLURRY IN THE VENT: IT'S NOT AN EXPERIMENT, STOP LEAVING IT THERE.",
            "[SIGNAL] MESS-HALL :: VENDING MACHINE 2 IS EATING CREDITS AGAIN. IF I LOSE ANOTHER FIVE CENTS, I'M REPLACING THE COIN SLOT WITH A MAGNET.",
            "[ANNOUNCE] CREW-CHAT :: REMINDER: ALL PERSONNEL MUST SUBMIT THEIR DIETARY RESTRICTIONS BY END OF WEEK FOR NEXT MONTH'S RATION CYCLE.",
            "[COMM] GALLEY-NET :: WHO TOLD THE COOK THAT 'MOLDY BREAD' IS A DELICACY? SOMEONE GET THE MEDICAL OFFICER IN HERE.",
            "[SIGNAL] MESS-CRU :: THE COFFEE MACHINE IS LEAKING BLACK SLUDGE ONTO THE FLOOR. WE ARE NOW SPRINTING THROUGH A HAZARD ZONE.",
            "[DATA] SUPPLY-LOG :: RATION SHIP DELAYED. EXPECT 48 HOURS OF 'EXTRA-THIN' PROTEIN CAKES UNTIL JUMP COMPLETION.",
            "[COMM] GALLEY-NET :: STOP STEALING THE STRAWBERRY SYRUP. IT IS FOR THE OFFICERS ONLY. GET YOUR OWN DECENT FLAVORING.",
            "[SIGNAL] MESS-HALL :: WHY IS THE SPOON DRAWER EMPTY? WHO IS USING THE UTENSILS AS PROXIMITY SENSORS FOR THEIR MECHS?",
            "[COMM] GALLEY-NET :: IF I FIND ONE MORE CRUMB IN THE RECYCLING BIN, I'M TURNING OFF THE HEAT IN THE LOWER DECKS.",
            "[ANNOUNCE] MESS-HALL :: MINIATURE PAINTING COMPETITION: SUBMIT YOUR BATTLEMASTER MODELS TO THE GALLEY DESK BY WEDNESDAY!",
            "[DATA] SUPPLY-LOG :: CAUTION: POTENTIAL CONTAMINATION IN THE SOY-PASTE VAT. DISCARD ALL LOTS MARKED 'BETA-9'.",
            "[COMM] GALLEY-NET :: I DON'T CARE IF YOU'RE A MAJOR, STOP TAKING THE LAST OF THE REAL CREAM.",
            "[SIGNAL] MESS-HALL :: THE MICROWAVE IS MAKING A SCREECHING SOUND. IT SOUNDS LIKE A DYING ENFORCER.",
            "[COMM] GALLEY-NET :: WHO LEFT THE SPICE JARS OPEN? NOW THE WHOLE DECK SMELLS LIKE ARTIFICIAL CINNAMON."
        ],
        maintenance: [
            "[SIGNAL] BARRACKS-3 :: STOP TAKING 20-MINUTE SHOWERS! WATER RECYCLING IS AT 40% CAPACITY. WE'RE ON A DROPSHIP, NOT A LUXURY CRUISE ON SOLARIS VII.",
            "[COMM] ENGINEERING :: TO THE PERSON WHO USED MY PRIVATE COFFEE STASH: I KNOW IT WAS YOU, MILLER. PAY UP OR WATCH YOUR BACK NEXT TIME WE JUMP.",
            "[SIGNAL] CMD-CHANNEL :: RECYCLING UNIT 4 IS CLOGGED AGAIN. STOP FLUSHING UNOFFICIAL GEAR. THE CHIEF IS FUMING.",
            "[DATA] CREW-CHAT :: WHO LEFT THEIR WET BOOTS IN THE MIDDLE OF THE CORRIDOR? I NEARLY BROKE MY NECK DURING THE LAST HIGH-G BURN.",
            "[SIGNAL] TECH-BAY :: THE HEAT SINK REPLACEMENT PARTS FOR THE ENFORCER ARE LATE AGAIN. IF WE HAVE TO FIGHT WITH HALF-CLOGGED RADIATORS, DON'T COMPLAIN WHEN THE PILOT PASSES OUT FROM HEAT STROKE.",
            "[COMM] ENGINEERING :: I DON'T CARE IF IT 'WORKS FOR NOW.' STOP PATCHING HYDRAULIC LEAKS WITH INDUSTRIAL DUCT TAPE. THIS IS A DROPSHIP, NOT A JUNKYARD SCAVENGER SHIP.",
            "[DATA] LOG-FILE :: WARNING: POWER SURGE IN SECTOR 7 DETECTED. THE SECONDARY GRID IS OPERATING AT 110% CAPACITY. STOP PLUGGING YOUR PERSONAL GAME CONSOLES INTO THE MAIN BUS.",
            "[SIGNAL] TECH-BAY :: WHO STOLE THE 10MM WRENCH? I NEED IT TO FIX THE VENTILATION BEFORE WE SUFFOCATE.",
            "[COMM] ENGINEERING :: HYDRAULIC FLUID LEVELS ARE CRITICAL. IF ANYONE USES AN EXTRA DROP FOR THEIR PERSONAL PROJECT, THEY'RE CLEANING THE REACTOR CORE.",
            "[SIGNAL] CMD-CHANNEL :: ALL MAINTENANCE TEAMS: REPORT TO HANGAR BAY 2 FOR EMERGENCY INSPECTION OF THE DROPSHIP STRUTS.",
            "[DATA] LOG-FILE :: SENSOR ARRAY DRIFT DETECTED. RECALIBRATION SCHEDULED FOR POST-JUMP.",
            "[COMM] TECH-NET :: THE SOLDERING IRON IS BROKEN. WHO TRIED TO USE IT TO HEAT UP THEIR LUNCH?",
            "[SIGNAL] ENGINEERING :: POWER GRID OVERLOAD IN SECTOR B. IF YOU'RE RUNNING A HIGH-POWER LASER IN YOUR QUARTERS, TURN IT OFF.",
            "[DATA] DECK-4 :: THE AIR RECLAMATION UNIT IS CLOGGED WITH HAIR AND DUST. CLEAN UP YOUR PERSONAL SPACES!",
            "[SIGNAL] TECH-BAY :: WE ARE OUT OF CONDUCTIVE GREASE. STOP USING ENGINE OIL ON THE CIRCUIT BOARDS.",
            "[COMM] ENGINEERING :: IF I SEE ONE MORE 'TEMPORARY' FIX ON THE MAIN REACTOR, I AM RETIRING TO A MINING COLONY.",
            "[DATA] LOG-FILE :: THERMAL OVERLOAD IN MECH-BAY 3. VENTILATION FANS ARE AT STALLED CAPACITY.",
            "[SIGNAL] TECH-NET :: THE DIAGNOSTIC COMPUTER IS RUNNING ON A LOOP. STOP REBOOTING IT EVERY TIME YOU WANT TO CHECK YOUR EMAIL.",
            "[COMM] ENGINEERING :: WHO LEFT THE ARC WELDER RUNNING IN THE CORRIDOR? YOU ALMOST MELTED THE FLOOR PLATING!",
            "[SIGNAL] CMD-CHANNEL :: REMINDER: ALL TOOLS MUST BE RETURNED TO THE CENTRAL LOCKER AT THE END OF EVERY SHIFT.",
            "[DATA] LOG-FILE :: HYDRAULIC PRESSURE DROPPING IN UNIT DELTA. SCHEDULE IMMEDIATE REPLACEMENT OF SEAL 4-B.",
            "[COMM] TECH-BAY :: STOP ASKING FOR NEW PARTS. WE ARE USING WHAT IS LEFT IN THE SCRAP BIN."
        ],
        deck: [
            "[DATA] PRIVATE-SEC :: HAS ANYONE SEEN MY DATA SLAB? IT HAD THE SEASON FINALE OF 'THE LORDS OF LUTHRIEN' ON IT.",
            "[SIGNAL] DECK-2 :: THE HOLODRAMA PROJECTOR IS SMOKING AGAIN. WHOEVER TRIED TO OVERCLOCK IT TO RUN 'BATTLEMECH GLADIATORS' IN 4K, YOU'RE PAYING FOR THE SPARE PARTS.",
            "[COMM] BRIDGE-SEC :: REMINDER: THE INTEL DESK IS NOT FOR NAP TIME. IF I FIND ANOTHER PILLOW IN THE TACTICAL STATION, IT'S GOING OUT THE AIRLOCK.",
            "[SIGNAL] REC-ROOM :: WHO CHANGED THE CHANNEL? WE WERE HALFWARD THROUGH THE STEINER OPERA. NO ONE WANTS TO WATCH URBIE-RACING RIGHT NOW.",
            "[ANNOUNCE] REC-ROOM :: REMINDER: THE 'IRON GRIP' MINIATURE WAR GAMES TOURNAMENT IS THIS SATURDAY. SIGN UPS ARE AT THE COMMAND DESK. NO EXEMPTIONS FOR OFFICERS!",
            "[DATA] PRIVATE-SEC :: THE INTERNET LATENCY DURING JUMP-SPACE TRANSITION IS UNBEARABLE. I CAN'T EVEN DOWNLOAD A SIMPLE STRATEGY GUIDE WITHOUT IT BUFFERING FOR THREE HOURS.",
            "[SIGNAL] DECK-2 :: TO THE PERSON WHO LEFT THEIR EMPTY AMMO CRATES IN THE RECREATION LOUNGE: CLEAN IT UP OR I'M USING THEM AS FOOTSTOOLS.",
            "[COMM] BRIDGE-SEC :: TACTICAL MAPS ARE BLURRY. IF THE NAV-COMPUTER ISN'T FIXED, WE ARE GOING TO FLY INTO A SUN.",
            "[SIGNAL] REC-ROOM :: WHO LEFT THEIR HALF-FINISHED MODEL KIT ON THE TABLE? IT'S TAKING UP SPACE FOR THE BOARD GAMES.",
            "[DATA] PRIVATE-SEC :: LOST: ONE LEFT BOOT. IF FOUND, RETURN TO DECK 4. REWARD: A VOUCHER FOR ONE FREE SYNTH-COFFEE.",
            "[ANNOUNLY] REC-ROOM :: MINIATURE PAINTING CONTEST: SHOW US YOUR BEST SHADING! PRIZE IS THE 'GOLDEN MECH' TROPHY AND NO DUTY FOR 24 HOURS.",
            "[SIGNAL] DECK-2 :: THE HOLO-PROJECTOR IS STUCK ON A LOOP OF THE EMPEROR'S BIRTHDAY SPEECH. SOMEONE REBOOT IT!",
            "[COMM] BRIDGE-SEC :: STOP LEAVING PERSONAL DATA SLABS ON THE COMMAND CONSOLE. THIS IS A WARSHIP, NOT A LIBRARY.",
            "[DATA] PRIVATE-SEC :: HAS ANYONE SEEN THE RECENT ISSUES OF 'SOLARIS MONTHLY'? I NEEDED THAT INTERVIEW WITH THE GLADIATOR.",
            "[SIGNAL] REC-ROOM :: NO LOUD MUSIC AFTER 2200 HOURS. SOME OF US ARE TRYING TO SLEEP BEFORE THE DROP.",
            "[COMM] BRIDGE-SEC :: THE SENSOR ARRAY IS ACTING UP AGAIN. IT KEEPS REPORTING GHOST SIGNATURES IN SECTOR 9.",
            "[DATA] PRIVATE-SEC :: WHOEVER LEFT THEIR DIRTY UNIFORM IN THE RECREATION LOUNGE... YOU ARE DISGRACE TO THE REGIMENT.",
            "[SIGNAL] DECK-2 :: THE HOLO-SCREEN IS PIXELATED. I CAN'T EVEN SEE THE FACE OF THE ACTOR!",
            "[ANNOUNCE] REC-ROOM :: REMINDER: THE UNIT CARD TRADING SESSION IS TONIGHT IN THE COMMON ROOM. BRING YOUR HIGHER-TIER CARDS!",
            "[COMM] BRIDGE-SEC :: TACTICAL READOUTS ARE DELAYED BY 2 SECONDS. CHECK THE COMM-LINK RELAYS.",
            "[SIGNAL] REC-ROOM :: STOP LEAVING YOUR BOARD GAME PIECES ALL OVER THE FLOOR. SOMEONE IS GOING TO STEP ON A D20."
        ],
        med_bay: [
            "[SIGNAL] MED-BAY :: STIM-PACK RESERVES ARE AT CRITICAL LEVELS. CEASE ALL NON-ESSENTIAL USE FOR MINOR SCRATCHES AND HEADACHES.",
            "[DATA] PATIENT-LOG :: SUBJECT 402 IS REFUSING TO REMOVE THE RADIOLOGICAL SUIT. SOMEONE ASSIST THE ORDERLY BEFORE HE RUINS THE CLEAN ROOM.",
            "[COMM] MED-STAFF :: IF ONE MORE PILOT TRIES TO SELF-TREAT A COCKPIT BURN WITH SYNTH-ALE, I AM CALLING THE COMMANDER.",
            "[SIGNAL] QUARANTINE :: DECONTAMINATION PROTOCOL 9 IS IN EFFECT FOR ALL PERSONNEL RETURNING FROM SURFACE OPERATIONS. NO EXCEPTIONS.",
            "[DATA] MED-LOG :: REPLENISH MORPHINE IMMEDIATELY. THE LAST BATCH WAS EXHAUSTED DURING THE LAST DROP.",
            "[COMM] NURSE-STATION :: TO THE PERSON WHO LEFT THE SURGICAL LASER ON 'MAX POWER' IN THE STORAGE BIN: YOU ALMOST SEVERED A DOCTOR'S HAND.",
            "[SIGNAL] MED-BAY :: RECALLING ALL BLOOD-REPLACEMENT BAGS FROM LOTTER-B. TESTING SHOWS TRACE CONTAMINATION.",
            "[DATA] PATIENT-LOG :: REMINDER: NO VISITATION IN THE CRITICAL CARE WARD DURING THE NIGHT SHIFT. KEEP THE NOISE DOWN.",
            "[COMM] MED-STAFF :: STOP BRINGING UNCLEAN MECH-SUITS INTO THE INFIRMARY. THE BACTERIA LOAD IS ALREADY TOO HIGH.",
            "[SIGNAL] BIO-SCAN :: ALERT: RADIATION LEAK DETECTED IN SECTOR 3 SURGERY SUITE. EVACUATE THE AREA IMMEDIATELY.",
            "[DATA] MED-LOG :: SECONDARY BANDAGE STOCK IS RUNNING LOW. START RECYCLING CLEAN SCRAP CLOTH UNTIL THE NEXT RESUPPLY.",
            "[COMM] MED-BAY :: TO THE PILOT IN BAY 4: STOP COMPLAINING ABOUT THE PAIN MEDICATIONS. YOU'RE LUCKY WE FOUND YOUR LEG AT ALL.",
            "[SIGNAL] CLINIC :: NEW PROTOCOL: ALL PERSONNEL WITH UNEXPLAINED SKIN IRRITATION MUST REPORT FOR SCANNING.",
            "[DATA] PATIENT-LOG :: POST-SURGERY RECOVERY RATES ARE DOWN 10%. CHECK THE HYDRATION LEVELS IN THE RECOVERY WARD.",
            "[COMM] MED-STAFF :: IF I SEE ONE MORE BLOOD-STAINED GLOVE LEFT ON THE COUNTER, I'M QUITTING AND JOINING THE PIRATES.",
            "[SIGNAL] BIO-SCAN :: WARNING: VIRAL SIGNATURE DETECTED IN HABITATION MODULE 2. PREPARE FOR LOCALIZED LOCKDOWN.",
            "[DATA] MED-LOG :: DISCARD ALL EXPIRED ANTIBIOTICS FROM THE LAST QUARTER. THE SHIP'S MEDICINE IS STARTING TO LOOK LIKE SUGAR.",
            "[COMM] NURSE-STATION :: REMINDER: DO NOT USE THE SURGICAL CLEANERS FOR PERSONAL HYGIENE. WE ARE RUNNING OUT.",
            "[SIGNAL] MED-BAY :: THE AUTO-REGENERATOR IN BAY 1 IS MALFUNCTIONING. IT'S CURRENTLY JUST REWINDING TIME BY TWO SECONDS.",
            "[DATA] PATIENT-LOG :: SUBJECT 109 IS AWAKE AND AGGRESSIVE. INCREASE SEDATION LEVELS IMMEDIATELY.",
            "[COMM] MED-STAFF :: WHO LEFT THE BIO-HAZARD WASTE IN THE HALLWAY? IT'S STARTING TO SMELL LIKE A DEATH WORLD.",
            "[SIGNAL] CLINIC :: ALL PERSONNEL ARE REMINDED THAT SURGICAL COFFEE IS STRICTLY FOR MEDICAL STAFF ONLY.",
            "[DATA] MED-LOG :: SHIPMENT OF REPLACEMENT STIM-PUMPS IS DELAYED. PREPARE FOR MANUAL INJECTION PROTOCOLS.",
            "[COMM] NURSE-STATION :: IF THE MEDICINE CABINET IS EMPTY AGAIN, I'M NOT LOOKING THE OTHER WAY DURING THE NEXT AUDIT."
        ],
        logistics_supply: [
            "[DATA] SUPPLY-LOG :: REQUISITION #882 FOR NEW AC/DC HEAT SINKS HAS BEEN DENIED. USE THE SECOND-HAND ONES FROM THE SCRAP BIN.",
            "[SIGNAL] LOGISTICS :: SHIPMENT OF 120MM SHELLS IS DELAYED DUE TO PIRATE ACTIVITY IN THE NEARBY NEBULA. ADJUST FIRE PLANS.",
            "[COMM] SUPPLY-OFFICER :: IF ANYONE ELSE 'FORGETS' TO LOG THEIR USED AMMO CASINGS, I WILL PERSONALLY AUDIT EVERY LOCKER ON THIS SHIP.",
            "[DATA] INVENTORY :: ALERT: FUEL RESERVES FOR THE DROPSHIP ARE AT 15%. CEASE ALL NON-ESSENTIAL MANEUVERS.",
            "[SIGNAL] CARGO-DECK :: UNIDENTIFIED CRATE ARRIVED WITHOUT A MANIFEST. DO NOT OPEN UNTIL TECHS CAN VERIFY CONTENTS.",
            "[COMM] SUPPLY-LOG :: THE ORDER FOR NEW MECH-SUITS WAS LOST IN TRANSIT. EXPECT A 2-WEEK DELAY.",
            "[DATA] REQ-STATUS :: REQUEST FOR 'PREMIUM GRADE' COFFEE IS OFFICIALLY CLASSIFIED AS A LUXURY AND WILL NOT BE FUNDED.",
            "[SIGNAL] LOGISTICS :: AUDIT COMMENCING ON ALL MECH-BAY SPARE PARTS. PLEASE HAVE YOUR LEDGERS READY BY 0600.",
            "[COMM] SUPPLY-OFFICER :: STOP STEALING THE PRECISION SCREWDRIVERS FROM THE SHIP'S MASTER KIT. THEY ARE NOT PERSONAL TOOLS.",
            "[DATA] LOG-FILE :: WARNING: COOLANT LEVELS IN MAIN RESERVOIR ARE DROPPING. CHECK FOR LEAKS IN THE ENGINE MANIFOLD.",
            "[SIGNAL] CARGO-DECK :: ALL PERSONNEL MUST CLEAR THE LOADING DOCK DURING THE NEXT UNLOADING CYCLE. NO EXCEPTIONS.",
            "[COMM] SUPPLY-LOG :: THE SHIPMENT OF REPLACEMENT ARMOR PLATING HAS BEEN DIVERTED TO THE COMMANDER'S PERSONAL RESERVES.",
            "[DATA] INVENTORY :: ALERT: WE ARE OUT OF CONDUCTIVE GREASE. STOP USING ENGINE OIL ON THE CIRCUIT BOARDS.",
            "[SIGNAL] LOGISTICS :: NOTICE: ALL UNUSED AMMO CRATES MUST BE RETURNED TO THE CENTRAL ARMORY AT END OF SHIFT.",
            "[COMM] SUPPLY-OFFICER :: WHOSE NAME IS ON THIS REQUISITION FOR 500 LBS OF ARTIFICIAL CHOCOLATE? EXPLAIN YOURSELF.",
            "[DATA] LOG-FILE :: TRACKING ERROR: 20 UNITS OF THERMAL HEAT SINKS ARE MISSING FROM THE LAST INVENTORY COUNT.",
            "[SIGNAL] CARGO-DEATK :: UNLOAD ALL HAZARDOUS MATERIALS IMMEDIATELY. DO NOT LEAVE CHEMICALS NEAR THE FUEL CELLS.",
            "[COMM] SUPPLY-LOG :: REQUISITION FOR 'BETTER QUALITY' RATIONS HAS BEEN REJECTED BY HIGH COMMAND. DEAL WITH IT.",
            "[DATA] INVENTORY :: ALERT: POWER CONDUIT REPLACEMENT PARTS ARE CURRENTLY OUT OF STOCK. USE TEMPORARY PATCHES ONLY.",
            "[SIGNAL] LOGISTICS :: SHIPMENT ARRIVAL DELAYED. THE CARRIER IS STUCK IN A JUMP-POINT TRAFFIC JAM.",
            "[COMM] SUPPLY-OFFICER :: STOP HIDING EXTRA PROTEIN BARS IN YOUR PERSONAL LOCKERS. I KNOW THEY'RE THERE.",
            "[DATA] REQ-STATUS :: REQUEST FOR NEW HYDRAULIC SEALS HAS BEEN PUSHED TO THE NEXT BUDGET CYCLE. GOOD LUCK WITH THE LEAKS.",
            "[SIGNAL] CARGO-DECK :: ALL UNIDENTIFIED DEBRIS IN THE LOADING BAY MUST BE REPORTED TO THE TECHS IMMEDIATLY.",
            "[COMM] SUPPLY-LOG :: IF THE SHIPMENT OF REPLACEMENT COCKPIT GLASS DOESN'T ARRIVE, WE ARE GOING TO BE FLYING BLIND."
        ]
    };

    // Select a set based on detachmentId, or mix them for the Command level
    const intercepts = useMemo(() => {
        let baseList: string[];
        if (!detachmentId) {
            baseList = [...interceptSets.galley, ...interceptSets.maintenance, ...interceptSets.deck, ...interceptSets.med_bay, ...interceptSets.logistics_supply];
        } else {
            const hash = (detachmentId || '').split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
            const sets = [interceptSets.galley, interceptSets.maintenance, interceptSets.deck, interceptSets.med_bay, interceptSets.logistics_supply];
            baseList = sets[hash % sets.length];
        }
        return [...baseList].sort(() => Math.random() - 0.5);
    }, [detachmentId]);

    const scrollRef = useRef<HTMLDivElement>(null);
    const [scrollDuration, setScrollDuration] = useState(80);

    useEffect(() => {
        if (scrollRef.current) {
            // The animation travels 50% of the total height (one full set of intercepts)
            const distanceToTravel = scrollRef.current.scrollHeight / 2;

            // Adjust this constant to set the global speed (pixels per second)
            const pixelsPerSecond = 20;

            const calculatedDuration = distanceToTravel / pixelsPerSecond;
            setScrollDuration(calculatedDuration);
        }
    }, [intercepts]);

    return (
        <div className="command-dashboard-bg" aria-hidden="true">
            <div className="bridge-overlay" />
            <div className="intercept-scroll" ref={scrollRef} style={{ animationDuration: `${scrollDuration}s` }}>
                {[...intercepts, ...intercepts].map((text, i) => (
                    <div key={i} className="intercept-line">{text}</div>
                ))}
            </div>
            <style>{`
                .command-dashboard-bg {
                    position: absolute;
                    top: 0; left: 0; width: 100%; height: 100%;
                    pointer-events: none;
                    z-index: -1;
                    overflow: hidden;
                }
                .bridge-overlay {
                    position: absolute;
                    top: 0; left: 0; width: 100%; height: 100%;
                    background-image: url('/dropship_schematic.svg');
                    background-size: contain;
                    background-repeat: no-repeat;
                    background-position: center;
                    opacity: 0.15;
                }
                .intercept-scroll {
                    position: absolute;
                    top: 20px; left: 20px;
                    width: 500px;
                    font-family: monospace;
                    font-size: 0.7rem;
                    color: var(--terminal-amber);
                    display: flex; flex-direction: column; gap: 15px;
                    animation: scroll-intel linear infinite;
                    white-space: normal;
                    text-transform: uppercase;
                    opacity: 0.15;
                    mask-image: linear-gradient(to bottom, black, transparent);
                }
                @keyframes scroll-intel {
                    0% { transform: translateY(0); }
                    100% { transform: translateY(-50%); }
                }
                .intercept-line {
                    padding-bottom: 8px;
                    padding-left: 1.5rem;
                    text-indent: -1.5rem;
                }
            `}</style>
        </div>
    );
};