-- Create campaigns table (Campaign.java)
CREATE TABLE IF NOT EXISTS campaigns (
    `id` VARCHAR(36) NOT NULL PRIMARY KEY,
    `name` VARCHAR(255),
    `manager_id` VARCHAR(36) NOT NULL,
    `status` VARCHAR(50),
    `system_name` VARCHAR(255),
    `description` TEXT,
    `track_count` INT,
    `length_in_months` INT,
    `pay_rate` DOUBLE,
    `pay_step` INT,
    `salvage_terms` VARCHAR(255),
    `salvage_step` INT,
    `support_terms` VARCHAR(255),
    `support_step` INT,
    `transport_terms` VARCHAR(255),
    `transport_step` INT,
    `command_rights` VARCHAR(255),
    `command_step` INT,
    `monthly_pay` INT DEFAULT 500,
    `monthly_maintenance` INT DEFAULT 500,
    `transportation_cost` INT DEFAULT 300,
    `combat_pay` INT DEFAULT 500,
    `armor_multiplier` DOUBLE,
    `internal_multiplier` DOUBLE,
    `crippled_multiplier` DOUBLE,
    `destroyed_multiplier` DOUBLE,
    `non_mech_modifier` DOUBLE,
    `mixed_tech_modifier` DOUBLE,
    `clan_tech_modifier` DOUBLE,
    `omnimech_reconfigure_modifier` DOUBLE,
    `purchase_unit_multiplier` INT,
    `sell_unit_multiplier` INT,
    `rearm_cost_per_ton` INT,
    `rearm_cost_per_ton_alpha_strike` INT,
    `hire_mechwarrior_cost` INT,
    `hire_named_pilot_cost` INT,
    `hire_battle_armor_cost` INT,
    `heal_mechwarrior_per_wound_box_cost` INT,
    `heal_mechwarrior_per_month_cost` INT,
    `heal_battle_armor_cost` INT,
    `train_formation_commander_cost` INT,
    `change_formation_training_cost` INT,
    `learn_first_ability_cost` INT,
    `learn_second_ability_cost` INT,
    `learn_third_ability_cost` INT,
    `replace_ability_cost` INT,
    CONSTRAINT fk_campaign_manager FOREIGN KEY (manager_id) REFERENCES app_users(id)
);
